# yaml-language-server: $schema=schema.json
# KeySwift Configuration File

mode_actions:
  default:
    if: "true"
    triggers:
      - source_event:
          key_press_event:
            key: "esc"
        action:
          set_value:
            normal: true
      - source_event:
          window_focus_event:
            window_class:
              - kitty
              - ghostty
        action:
          set_value:
            terminal: true
  normal:
    if: normal
    triggers:
      - source_event:
          key_press_event:
            key: "j"
        action:
          map_to_keys:
            keys:
              - key: "down"
      - source_event:
          key_press_event:
            key: "k"
        action:
          map_to_keys:
            keys:
              - key: "up"
      - source_event:
          key_press_event:
            key: "i"
        action:
          set_value:
            normal: false
  terminal:
    if: terminal
    triggers:
      - source_event:
          key_press_event:
            key: "j"
        action:
          map_to_keys:
            keys:
              - key: "down"
