name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up libevdev
        run: sudo apt-get install libevdev-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache-dependency-path: go.sum

      - name: Build
        run: |
          make
          chmod +x keyswift
          tar -czvf keyswift-linux-amd64.tar.gz keyswift

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: keyswift-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
